author: {{ cookiecutter.full_name }}
github_url: https://github.com/{{ cookiecutter.github_name }}/{{ cookiecutter.name }}
root_url: https://{{ cookiecutter.github_name }}.github.io/{{ cookiecutter.name }}/
module: {{ cookiecutter.name }}
output: docs
theme: fullwidth
xcodebuild_arguments: [-workspace, '{{ cookiecutter.name }}.xcworkspace', -scheme, '{{ cookiecutter.name }}-iOS']
