language: objective-c
osx_image: xcode9.2
branches:
  only:
  - master
  - develop
  - "/^X\\d+(.\\d+)?\\/S\\d+(.\\d+)?$/"
before_install:
- brew update
- brew install cookiecutter
- cookiecutter -c develop --no-input https://github.com/ddrccw/FrameworkTemplate
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Framework.xcworkspace
  - IOS_FRAMEWORK_SCHEME="Framework-iOS"
  matrix:
  - DESTINATION="OS=11.2,name=iPhone X"                   SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="YES"
  - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"            SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="YES"
  - DESTINATION="OS=9.0,name=iPhone 6"                    SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="YES"
  - DESTINATION="OS=8.1,name=iPhone 5s"                   SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="YES"
before_script:
- cd Framework
script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- if [ $RUN_TESTS == "YES" ]; then
    xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES
  test | xcpretty -c;
  else
    xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
  fi
- if [ $RUN_TESTS == "YES" ]; then
    xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
  else
    xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
  fi
jobs:
  include:
  - stage: Pod lib lint
    script: pod lib lint --verbose --allow-warnings
  - stage: deploy
    before_deploy: carthage build --no-skip-current && carthage archive Framework
    deploy:
    - provider: releases
      api_key:
        secure: 1c07fb511efe36f071a927bbbb24c704aad93229
      file:
      - Framework.framework.zip
      skip_cleanup: true
      overwrite: true
      on:
        repo: ddrccw/FrameworkTemplate
        tags: true
