source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

workspace 'FRAMEWORKNAME'

target 'FRAMEWORKNAME-iOS' do

    target 'FRAMEWORKNAMETests-iOS' do
    end

    target 'FRAMEWORKNAME-Demo' do
    end

end



